# See full Decap documentation for further configuration: https://decapcms.org/docs/intro/
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: src/assets/images/uploads # Location where files will be stored in the repo - we store them in src so that Astro can optimize them.
public_folder: src/assets/images/uploads  # Ensure that this path is the same as the media_folder path above.
site_url: https://breathwaveireland.com/ # Displays a link to home page in the top-right corner of the CMS dashboard

collections:
  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Payment Link", name: "paymentLink", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["events"] }
      - { label: "Location", name: "location", widget: "string" }
  - name: "podcasts"
    label: "Podcasts"
    folder: "src/content/podcasts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Guest", name: "guest", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["podcasts"] }
      - { label: "URL", name: "url", widget: "string" }
